#!/usr/bin/env sh
set -eu

port="${GAKAI_PORT:-3000}"
host="${GAKAI_PUBLIC_HOST:-gakai.localhost}"

case "$port" in
  *[!0-9]*|"" ) echo "GAKAI_PORT must be a number (for example: GAKAI_PORT=8080)." >&2; exit 2 ;;
esac

if [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
  echo "GAKAI_PORT must be between 1 and 65535." >&2
  exit 2
fi

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  echo "Docker Desktop or Docker Engine with the Compose plugin is required." >&2
  exit 1
fi

gen_secret() { openssl rand -hex 32 2>/dev/null || od -An -N32 -tx1 /dev/urandom | tr -d " \n"; }

if [ ! -f .env ] || ! grep -q "^GAKAI_PROVIDER_API_KEY=." .env; then
  (umask 077; printf "\n# Generated by Gakai. Do not share or commit this file.\nGAKAI_PROVIDER_API_KEY=%s\n" "$(gen_secret)" >> .env)
  echo "Created private runtime configuration."
fi

if ! grep -q "^GAKAI_PROVIDER_WEBHOOK_SECRET=." .env 2>/dev/null; then
  (umask 077; printf "GAKAI_PROVIDER_WEBHOOK_SECRET=%s\n" "$(gen_secret)" >> .env)
fi

port_in_use() {
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | grep -q ":$1 "
  elif command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$1" -sTCP:LISTEN -t >/dev/null 2>&1
  fi
}

if port_in_use "$port"; then
  echo "Port $port is already in use. Choose another port, for example:" >&2
  echo "  GAKAI_PORT=8080 ./scripts/gakai-up.sh" >&2
  exit 1
fi

export GAKAI_PORT="$port"
export GAKAI_PUBLIC_HOST="$host"
docker compose up -d --build

echo
echo "Gakai is starting. Open: http://$host:$port"
echo "Check readiness: http://$host:$port/readyz"
